Zkitefly patch 1
wifi-left/HMCL-docs-website pull request #30
Opened 2022-03-20 03:05 UTC by zkitefly

别再拒绝合并了TAT

2022-03-20 03:33 UTC, wifi-left approved these changes

2022-03-20 03:36 UTC, wifi-left requested changes

2022-03-20 03:36 UTC, wifi-left commented on pages/multiplayer-help.md
> +![多人联机界面](/pages/assets/img/docs/multiplayer/help/img1.png)
此文件不能这么修改，会出问题

2022-03-20 03:42 UTC, zkitefly commented on pages/multiplayer-help.md
> +![多人联机界面](/pages/assets/img/docs/multiplayer/help/img1.png)
改好了

2022-03-20 03:44 UTC, zkitefly commented on pages/multiplayer-help.md
> +![多人联机界面](/pages/assets/img/docs/multiplayer/help/img1.png)
这下可以合并了吧……

2022-03-21 04:09 UTC, zkitefly commented
TAT

能合并吗， https://github.com/huanghongxun/HMCL/pull/1400 引用了 链接需要合并！！！

TAT

2022-03-21 06:11 UTC, wifi-left commented
> TAT
> 
> 能合并吗， [huanghongxun/HMCL#1400](https://github.com/huanghongxun/HMCL/pull/1400) 引用了 链接需要合并！！！
> 
> TAT

不能

> 就像黄鱼说的：不要搞合并 pull request 这种事

2022-03-21 06:11 UTC, closed without merging

2022-03-21 06:15 UTC, wifi-left commented
如果可以，请增加添加的文件，旧文件暂时不要修改。
`mulitiplay-faq` 写的有点杂乱，暂时不加。

2022-03-21 13:39 UTC, zkitefly commented
QAQ

2022-03-22 02:13 UTC, wifi-left commented
https://github.com/wifi-left/HMCL-docs-website/blob/main/pages/contribution.md

2022-03-22 04:40 UTC, zkitefly commented
那我一点点提交把……